import './globals.css'
import Navbar from '../components/Navbar'

import ThemeContext from './context/ThemeContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeContext>

          <Navbar />
          {children}

        </ThemeContext>
        </body>
    </html>
  )
}
